### ISSUE TITLE
Export Plots to X11/XQuartz window?

### ISSUE THREAD

**Issue by BlueGrisGris** [luk400/vim-jukit#10]
I have been looking for a long time for a vim plugin that accomplishes what this one does, thank you for the wonderful project!

So far the big thing that would improve it for me would be some way of sending matplotlib plots to an X11/XQuartz, instead of having them pop up in a python plot window.  The python plot window seems to prevent new commands from being sent to the ipython terminal.  For example, to rerun code that generates a plot with new inputs, I have to switch to the python plot instance and close it out, and then return to vim to rerun the code.   X windows also work well with ssh.

I am looking into kitty, but I am not sure I want to commit to it just yet.

Thanks for your thoughts!

**Comment by luk400** [comment]
This should now work using `plt.show(block=False)`. If you use `plt.show(block=False)`, you should be able to simply rerun the cell without having to close the window.

If you want to have multiple different plots and show them mid-execution, this should also be possible now. Here are a few examples:
* If you want to have a single window opened where a new figure is drawn each time: 
```python
import matplotlib.pyplot as plt
import time

for i in range(3):
    plt.plot([-1,i,3])

    plt.show(block=False)

    print('** some computations **')

    time.sleep(1)
    plt.gcf().clear()

```
or alternatively the following does the same:

```python
import matplotlib.pyplot as plt
import time

for i in range(3):
    f = plt.figure(0)
    plt.plot([-1,i,3])

    plt.show(block=False)

    print('** some computations **')

    time.sleep(1)
    f.clear()
```
* if you want a new window opened for each plot:
```python
import matplotlib.pyplot as plt
import time

for i in range(3):
    f = plt.figure(i)
    plt.plot([-1,i,3])

    plt.show(block=False)

    print('** some computations **')

    time.sleep(1)
```
* if you want to update an existing figure mid execution:
```python
import matplotlib.pyplot as plt
import time

for i in range(3):
    plt.plot([-1,i,3])

    # use block=False
    plt.show(block=False)

    print('** some computations **')

    time.sleep(1)
```

I could also make an option to use `block=False` as default in the matplotlib show wrapper, so that you don't have to specify `block=False` yourself each time when writing code.

**Comment by luk400** [comment]
You can now specify `g:jukit_mpl_block=0` in your vim config, so that every time you use `plt.show()` it'll be the same as explicitly calling `plt.show(block=False)`.

> I do not have experience with writing vim plugins, but if you are looking for contributors, I can start trying to learn.

Thank you very much for the offer, I'm always happy about contributions, so if you notice anything in the future that needs fixing and know how to do it, or have an idea for a feature you want to implement, feel free to make a pull request anytime.

Btw. I've corrected the first two of the non-blocking plot examples in my comment above (figures should've been cleared before calling `plt.plot()`, not afterwards, otherwise you'll end up with an additional empty figure at the end)
