### ISSUE TITLE
ModuleNotFoundError: No module named 'ipynb_convert'

### ISSUE THREAD

**Issue by PetarKotsev** [luk400/vim-jukit#17]
Hi all, 
I'm trying to set up the extension on Windows 11 (Windows Terminal). I have checked the requirements:
- NVIM: v0.7.2
- Python: 3.9.13
- IPython: 8.2.0
- Matplotlib: installed

The error I am given is the following:
![image](https://user-images.githubusercontent.com/15075546/180645811-7f433c26-6d48-410f-9adb-e748ec5ab902.png)

I would be very grateful to receive your suggestions.
Many thanks for considering my request.

**Comment by luk400** [comment]
Hi, yeah the plugin was not developed with Windows in mind. The error you're seeing is probably due to some of the paths being hardcoded with '/' instead of '\', thus it fails to add the directory of the plugin modules to your system path in python. This should be an easy fix, but I'll still have to test whether all the features work as expected on Windows. 
I'll get to it sometime this week as soon as I can get a Windows VM up and running

**Comment by luk400** [comment]
You can try again and see if it works as expected now, I tested the basic functionality on Windows 10 in PowerShell and got it working, let me know if you have any issues. Also make sure `python3` is a valid command in your terminal (and not just `python`), otherwise you'll need to specify `let g:_jukit_python_os_cmd = 'python'` in your vim config.
