### ISSUE TITLE
Enabling textcell-highlighting messes up neovim's spell 

### ISSUE THREAD

**Issue by igorlfs** [luk400/vim-jukit#28]
Hello there,

Recently, neovim added spell checking support for treesitter. However, when coupling treesitter with the built-in syntax highlighting, spell stops working as intended (i.e., code is spell checked). Enabling textcell-highlighting makes spell unusable in every file, not only in python and notebooks, which is a huge bummer. 

On the other hand, if you want to support neovim specific features, it would be nice if instead of using a syntax file to highlight, we had a treesitter injection. RegEx highlighting works just fine in Markdown, so it could feel like it costs more than it's worth, but I'm most certain it would solve the issue with spell.

**Comment by luk400** [comment]
Hi, I'm not using spellcheck, but I'll look into the issue sometime this week when I have time and will report back as soon as I know more

**Comment by luk400** [comment]
> Enabling textcell-highlighting makes spell unusable in every file, not only in python and notebooks, which is a huge bummer.

Just as an aside, you should be able to only enable the textcell-highlighting for python files by specifying `let g:jukit_hl_ext_enabled = ['py']` in your config- though that shouldn't be necessary, I think I fixed the problem now.
I believe the issue was that when loading the markdown syntax file, `syntax spell` is being set to `toplevel`, which causes the code to be spell checked. I now specifically set  `syntax spell` to `default` after loading the markdown syntax file, which should solve this problem. Please reinstall/update the plugin and check if it now works correctly for you.

I currently don't have time to look into treesitter in more detail, so a proper treesitter implementation of the textcell highlighting will have to wait for now.

**Comment by igorlfs** [comment]
> Just as an aside, you should be able to enable the textcell-highlighting for only python files 

Thanks for the tip!

> I think I fixed the problem now

Indeed! Working fine here :)

> I currently don't have time to look into treesitter in more detail, so a proper treesitter implementation of the textcell highlighting will have to wait for now.

How do you want to track this? Should I close this issue and open another one?

**Comment by luk400** [comment]
> Indeed! Working fine here :)

Great :)

> Should I close this issue and open another one?

Yeah that would be great, thank you

**Comment by Konfekt** [comment]
This is fixed on Neovim, but on Vim spell checking only works with `let g:jukit_enable_textcell_syntax = 0`.
