### ISSUE TITLE
Open REPL in vim's project root

### ISSUE THREAD

**Issue by egolep** [luk400/vim-jukit#4]
I don't know if it is explained somwhere, but I can't find a way to open the REPL in the same folder vim is using as project root.

**Comment by luk400** [comment]
Not quite sure if I understand you correctly, maybe you can clarify what exactly your expected behaviour is. 

For the builtin vim/neovim terminals, the working directory of the REPL will be whatever vims working directory currently is (`:pwd`).
For kitty, the working directory of the REPL will be the same directory from which you started vim. 

I'm guessing you're using kitty and the behaviour you're  expecting is the one I described for the builtin terminals?

**Comment by egolep** [comment]
Yeah, I've been pretty obscure in my explanation.
The setting and the expected behavior is exactly the one you wrote: I'm using kitty and I would like to have the new terminal/REPL opened in the current working directory.

**Comment by luk400** [comment]
Alright, that makes sense, thank you. I've now changed it so that kitty splits are explicitly launched in vim/neovims current cwd. Please reinstall the plugin and see if it now behaves as you'd expect.

**Comment by egolep** [comment]
It now works flawlessly, thanks for the quick fix and for this great plugin!
