### ISSUE TITLE
Any way to not display the entire input code cell in the iPython window when running a cell?

### ISSUE THREAD

**Issue by Thjalfe** [luk400/vim-jukit#47]
Hi, thank you for your nice plugin :)

As the title suggests, I would like to not see the entire code cell in the iPython window when running a code cell. From how I understand the documentation, I think that the g.jukit_show_prompt setting should enable this. But, changing this does not hide any input code in the iPython window. 
I use Kitty as my terminal and use the split layout.

Have I understood the setting correctly, is it not currently possible or is there another reason that it does not work for me?
Please tell me if you need other information.

Thanks!

**Comment by luk400** [comment]
Hi, I'm afraid you misunderstood what `g:jukit_show_prompt` does. This just controls whether you want to hide the ipython prompt (i.e. `In [1]: %jukit_run`) when executing code cells. Here how it looks with `g:jukit_show_prompt = 1`:

![image](https://user-images.githubusercontent.com/57172028/209874624-fcd321c0-7820-42c2-94c1-f7595d4436a6.png)

vs `g:jukit_show_prompt = 0`:

![image](https://user-images.githubusercontent.com/57172028/209874924-aba358df-c85a-406d-972f-48a673a575ce.png)

What you're looking for is `g:jukit_in_style`, which controls how the input should be displayed. I've now added 2 new styles which should do what you want. Specify `let g:jukit_in_style = 5` in your config (before the plugin is loaded) so that the input is not shown at all anymore. Specify `let g:jukit_in_style = 6` to at most show the first 7 lines of the input. If you wish to use a different style you can easily modfiy or define your own style in [<plugin_path>/vim-jukit/helpers/jukit_run/input_styles.py](https://github.com/luk400/vim-jukit/blob/master/helpers/jukit_run/input_styles.py).
Hope this helps!

**Comment by Thjalfe** [comment]
Thank you, this was just what I was looking for!
