### ISSUE TITLE
Config option to save html somewhere other than /tmp

### ISSUE THREAD

**Issue by JudsenHembree** [luk400/vim-jukit#52]
# snap bug
I'm running the latest ubuntu, and that ships with a snap version of firefox. When trying to launch notebook from a .py file. Everything works up until firefox tries to grab the html from /tmp. It can't see it. If you could add some option to save to a different dir than /tmp that would help. Also maybe describe this bug in the readme for other ubuntu users. 

## I did some digging
Looks like snap intentionally does not allow for it's packages to see the /tmp folder and thus it can't collect the html it needs. 
Here is a link -> https://forum.snapcraft.io/t/accessing-tmp-from-snaps/22384 The link mentions how apparently firefox can't see /tmp but can see /Downloads. 

## Verification of problem
Sure enough if I copy over that html to downloads I can open it from terminal with firefox and it appears as expected.

**Comment by JudsenHembree** [comment]
Problem goes away when using a non-snap version of Firefox

**Comment by luk400** [comment]
Hi, thanks for the information. I don't think there's anything I can do about this, since I'm not actively saving anything in /tmp, it seems the `jupyter notebook` command uses the /tmp directory and there doesn't seem to be an argument to change this behaviour. 
I'll add this to the readme however, thanks for letting me know!
